# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainmenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainmenu(object):
    def setupUi(self, mainmenu):
        mainmenu.setObjectName("mainmenu")
        mainmenu.resize(1440, 1024)
        mainmenu.setMinimumSize(QtCore.QSize(1440, 1024))
        mainmenu.setMaximumSize(QtCore.QSize(1440, 1024))
        mainmenu.setFocusPolicy(QtCore.Qt.NoFocus)
        mainmenu.setAutoFillBackground(False)
        mainmenu.setStyleSheet("background-image: url(:/back/sprites/mainmenu.png);\n"
"font: 75 48pt \"Amatic SC\";\n"
"")
        self.centralwidget = QtWidgets.QWidget(mainmenu)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.Play = QtWidgets.QPushButton(self.centralwidget)
        self.Play.setGeometry(QtCore.QRect(560, 450, 329, 89))
        self.Play.setMinimumSize(QtCore.QSize(329, 89))
        self.Play.setMaximumSize(QtCore.QSize(329, 89))
        self.Play.setAutoFillBackground(False)
        self.Play.setStyleSheet("QPushButton{\n"
"background-image: url(:/back/sprites/btplay.png);\n"
"border: none;\n"
"border-radus: 9px;}\n"
"\n"
"QPushButton:hover{\n"
"border: none;\n"
"border-radus: 9px;\n"
"}\n"
"\n"
"")
        self.Play.setText("")
        self.Play.setObjectName("Play")
        self.Settings = QtWidgets.QPushButton(self.centralwidget)
        self.Settings.setGeometry(QtCore.QRect(560, 570, 329, 89))
        self.Settings.setMinimumSize(QtCore.QSize(329, 89))
        self.Settings.setMaximumSize(QtCore.QSize(329, 89))
        self.Settings.setStyleSheet("QPushButton{\n"
"background-image: url(:/back/sprites/btsettings.png);\n"
"border: none;\n"
"border-radus: 9px;}\n"
"QPushButton:hover{\n"
"border: none;\n"
"border-radus: 9px;\n"
"}")
        self.Settings.setText("")
        self.Settings.setObjectName("Settings")
        self.Rules = QtWidgets.QPushButton(self.centralwidget)
        self.Rules.setGeometry(QtCore.QRect(560, 690, 329, 89))
        self.Rules.setMinimumSize(QtCore.QSize(329, 89))
        self.Rules.setMaximumSize(QtCore.QSize(329, 89))
        self.Rules.setStyleSheet("QPushButton{\n"
"background-image: url(:/back/sprites/btrules.png);\n"
"border: none;\n"
"border-radus: 9px;}\n"
"QPushButton:hover{\n"
"border: none;\n"
"border-radus: 9px;\n"
"}")
        self.Rules.setText("")
        self.Rules.setObjectName("Rules")
        self.Exit = QtWidgets.QPushButton(self.centralwidget)
        self.Exit.setGeometry(QtCore.QRect(560, 810, 329, 89))
        self.Exit.setMinimumSize(QtCore.QSize(329, 89))
        self.Exit.setMaximumSize(QtCore.QSize(329, 89))
        self.Exit.setStyleSheet("QPushButton{\n"
"background-image: url(:/back/sprites/btexit.png);\n"
"border: none;\n"
"border-radus: 9px;}\n"
"QPushButton:hover{\n"
"border: none;\n"
"border-radus: 9px;\n"
"}")
        self.Exit.setText("")
        self.Exit.setObjectName("Exit")
        mainmenu.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainmenu)
        QtCore.QMetaObject.connectSlotsByName(mainmenu)

    def retranslateUi(self, mainmenu):
        _translate = QtCore.QCoreApplication.translate
        mainmenu.setWindowTitle(_translate("mainmenu", "Подушечки из котиков"))
import background
